#!/usr/bin/env bash
# Copies web/analytics-parse.js verbatim into the marked <script> block in both
# pages that read the analytics API.
#
# It is inlined rather than linked because showcase.html is served from two
# origins -- the apex and the content host -- and a <script src="/..."> resolves
# on one and 404s on the other. Two copies only stay honest if divergence breaks
# a check, so --check runs from scripts/check-docs-sync.sh.
#
#   write:  bash scripts/inline-analytics-parser.sh
#   check:  bash scripts/inline-analytics-parser.sh --check
set -u
cd "$(dirname "$0")/.."

SRC=web/analytics-parse.js
BEGIN='/* BEGIN web/analytics-parse.js -- generated by scripts/inline-analytics-parser.sh; edit the source, not this copy */'
END='/* END web/analytics-parse.js */'
PAGES="internal/handler/static/index.html internal/handler/static/showcase.html internal/handler/static/analytics.html"

# The block is written at column 0 so the inlined bytes are identical to the
# source and the check is a plain diff.
gen() {
  awk -v src="$SRC" -v b="$BEGIN" -v e="$END" '
    {
      if (index($0, b)) { print; while ((getline line < src) > 0) print line; close(src); skip=1; next }
      if (skip) { if (index($0, e)) { print; skip=0 }; next }
      print
    }
  ' "$1"
}

check=0
[ "${1:-}" = "--check" ] && check=1

status=0
for page in $PAGES; do
  if ! grep -qF "$BEGIN" "$page" || ! grep -qF "$END" "$page"; then
    echo "  FAIL: $page has no generated parser block (markers missing)"
    status=1
    continue
  fi
  if [ "$check" -eq 1 ]; then
    if ! gen "$page" | diff -q - "$page" >/dev/null; then
      echo "  FAIL: $page's inlined parser differs from $SRC"
      status=1
    fi
  else
    gen "$page" > "$page.tmp" && mv "$page.tmp" "$page"
    echo "  wrote $page"
  fi
done

if [ "$check" -eq 1 ] && [ "$status" -ne 0 ]; then
  echo "  regenerate it:  bash scripts/inline-analytics-parser.sh"
fi
exit $status
